# Generated by Django 5.0.7 on 2024-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
